// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATX5QFGqcbGq-bjWuhwSVqJlHRsg6NayY',
    appId: '1:454626261608:web:5a06becfc60f2af13559dd',
    messagingSenderId: '454626261608',
    projectId: 'finova-e6958',
    authDomain: 'finova-e6958.firebaseapp.com',
    storageBucket: 'finova-e6958.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbzZMTZXvyFAAQpYmIV_iLAd7aKnzyqjo',
    appId: '1:454626261608:android:f317965de6c3f10f3559dd',
    messagingSenderId: '454626261608',
    projectId: 'finova-e6958',
    storageBucket: 'finova-e6958.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyTmiVDTfHf90dRlK3a0y2AfM0gK4JYGQ',
    appId: '1:454626261608:ios:59174d5e87e460273559dd',
    messagingSenderId: '454626261608',
    projectId: 'finova-e6958',
    storageBucket: 'finova-e6958.firebasestorage.app',
    iosBundleId: 'com.example.finova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyTmiVDTfHf90dRlK3a0y2AfM0gK4JYGQ',
    appId: '1:454626261608:ios:59174d5e87e460273559dd',
    messagingSenderId: '454626261608',
    projectId: 'finova-e6958',
    storageBucket: 'finova-e6958.firebasestorage.app',
    iosBundleId: 'com.example.finova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATX5QFGqcbGq-bjWuhwSVqJlHRsg6NayY',
    appId: '1:454626261608:web:41d70e702ac35a0f3559dd',
    messagingSenderId: '454626261608',
    projectId: 'finova-e6958',
    authDomain: 'finova-e6958.firebaseapp.com',
    storageBucket: 'finova-e6958.firebasestorage.app',
  );
}
